### ISSUE TITLE
Caesar Cipher

### ISSUE THREAD

**Issue by codyesm** [jfrommeyer5/CryptoHelperCSC439#5]
-Encipher English with the Caesar Cipher, requests the shift amount from the user.

**Comment by nmrogers** [comment]
Also handled value rollover for unicode characters to maintain caesar styled wrap-around for shifting.

**Comment by nmrogers** [comment]
To Implement:
-Decryption process
-Remove Symbol alerts.

**Comment by nmrogers** [comment]
Implemented successfully
